format = """
$username\
$hostname\
$directory\
$hg_branch\
$kubernetes\
$package\
$golang\
$python\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[kubernetes]
symbol = "⛵ "
style = "purple"
disabled = false

[golang]
symbol = "Go "
